#!/bin/bash
# Initial wifi interface configuration
# usage iniSoftAP FakeAP_NAME RealAP_NAME
FakeAP=wlan1
FORWARD=eth0

ifconfig $FakeAP down
ifconfig $FakeAP 10.0.0.1 netmask 255.255.255.0


#Enable NAT
iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain

iptables --table nat --append POSTROUTING --out-interface $FORWARD -j MASQUERADE


iptables --append FORWARD --in-interface $FakeAP -j  NFQUEUE --queue-num 0
iptables --append FORWARD --out-interface $FakeAP -j  NFQUEUE --queue-num 0


sysctl -w net.ipv4.ip_forward=1

#start hostapd
if [ "$(ps -e | grep hostapd)" == "" ]; then
	hostapd -B ./hostapd.conf 1>/dev/null 
fi

#Start DHCP
if [ "$(ps -e | grep dhcpd)" == "" ]; then
	dhcpd $FakeAP  1>/dev/null & 
fi
