#!/bin/bash
if [ "$(ps -e | grep dhcpd)" != "" ]; then
	kill $(ps -el | grep dhcpd | awk '{print $4}')
fi

if [ "$(ps -e | grep hostapd)" != "" ]; then
	kill $(ps -el | grep hostapd | awk '{print $4}')
fi

iptables --flush
iptables --table nat --flush
iptables --delete-chain
iptables --table nat --delete-chain

sysctl -w net.ipv4.ip_forward=0
